   # This is a basic workflow to help you get started with Actions

name: First Cron Job

       # Controls when the workflow will run
on:
  schedule:
    - cron: "5 * * * *"

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world 2 ! :wave:
            pr_number: 1 # This will comment on pull request #123
